services:
  - type: web
    name: ai-book-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: WEAVIATE_URL
        value: https://your-weaviate-instance.weaviate.network
