name: Deploy JosefGPT to Streamlit Cloud

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit app (build check)
        run: |
          streamlit run app/ui.py --server.headless true &
          sleep 10
          pkill streamlit

      - name: Deploy to Streamlit Cloud
        run: |
          echo "✅ Streamlit app verified. Ready to deploy."
          echo "⚠️ Note: Deploy is triggered automatically by Streamlit Cloud when new commits appear on main branch."
